#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for notification services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global vars for parent and subcharts.
# registration.endpoint.host: registration.{namespace}.svc.{cluster-domain}

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

global:
  namespace: notification

registration:
  imagePullSecrets: default-registry-key
  image:
    repository: rabbitmq
    tag: 3.8.11-management
    pullPolicy: IfNotPresent
  endpoint:
    host: "registration.notification.svc.cluster.local"
    port: 5672
    user: admin
    pass: admin
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ptp-registration
            operator: In
            values:
            - "true"

notification:
  image:
    repository: rabbitmq
    tag: 3.8.11-management
  endpoint:
    port: 5672
    user: admin
    pass: admin
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ptp-notification
            operator: In
            values:
            - "true"

location:
  image:
    repository: starlingx/locationservice-base
    tag: stx.5.0-v1.0.1
    pullPolicy: IfNotPresent

ptptracking:
  imagePullSecrets: default-registry-key
  ptp4lSocket: /var/run/ptp4l-legacy
  ptp4lServiceName: ptp4l-legacy
  phc2sysServiceName: phc2sys-legacy
  image:
    repository: starlingx/notificationservice-base
    tag: stx.7.0-v1.0.5
    pullPolicy: IfNotPresent
  device:
    simulated: false
    holdover_seconds: 15
    poll_freq_seconds: 2
